"""
Meta overlay: SQLite-backed metadata for files and folders (tags, etc.) without touching the filesystem.

Uses path + inode (and device) for cross-reference and validation. Records only exist for paths
that have metadata; the rest of the filesystem has no rows.
"""

from .db import (
    init_db,
    add_tag,
    remove_tag,
    get_tags,
    get_all_tagged_paths,
    get_all_tags,
    get_paths_by_tag,
    get_paths_by_tag_null,
    get_tag_nulls,
    get_path_meta,
    path_matches_meta,
    get_tags_from_rules,
    get_ancestor_tags,
    get_all_rules,
    add_rule_tag,
    remove_rule_tag,
    remove_rule_pattern,
    update_rule_pattern,
    add_tag_null,
    remove_tag_null,
    get_hidden_tags,
    add_hidden_tag,
    remove_hidden_tag,
    add_virtual_folder,
    get_virtual_children,
    set_vpath,
    generate_commands,
    get_entries_by_vpath_parent,
    get_meta_by_vpath,
    get_all_meta_for_debug,
    get_moved_in_scopes,
)

__all__ = [
    "init_db",
    "add_tag",
    "remove_tag",
    "get_tags",
    "get_all_tagged_paths",
    "get_all_tags",
    "get_paths_by_tag",
    "get_paths_by_tag_null",
    "get_tag_nulls",
    "get_path_meta",
    "path_matches_meta",
    "get_tags_from_rules",
    "get_ancestor_tags",
    "get_all_rules",
    "add_rule_tag",
    "remove_rule_tag",
    "remove_rule_pattern",
    "update_rule_pattern",
    "add_tag_null",
    "remove_tag_null",
    "get_hidden_tags",
    "add_hidden_tag",
    "remove_hidden_tag",
    "add_virtual_folder",
    "get_virtual_children",
    "set_vpath",
    "generate_commands",
    "get_entries_by_vpath_parent",
    "get_meta_by_vpath",
    "get_all_meta_for_debug",
    "get_moved_in_scopes",
]
